package dev.cvkulkarnidev.a2ui

data class A2UIExample(val name: String, val description: String, val jsonl: String)

val A2UI_EXAMPLES = listOf(
    A2UIExample(
        "Flight boarding pass",
        "Travel card with route, status, timing and action",
        """{"version":"v0.9","createSurface":{"surfaceId":"flight","catalogId":"basic","sendDataModel":true}}
{"version":"v0.9","updateDataModel":{"surfaceId":"flight","value":{"title":"Your next flight","route":"Pune → Bengaluru","airline":"IndiGo 6E 681","date":"20 Jul · 07:35","gate":"Gate 4","seat":"12A","duration":"1h 30m"}}}
{"version":"v0.9","updateComponents":{"surfaceId":"flight","components":[{"id":"root","component":"Column","spacing":14,"children":["hero","statusRow","routeCard","stats","divider","checkin"]},{"id":"hero","component":"Image","url":"https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200","alt":"Airplane wing"},{"id":"statusRow","component":"Row","justify":"spaceBetween","children":["title","status"]},{"id":"title","component":"Text","text":{"path":"/title"},"variant":"h2"},{"id":"status","component":"Chip","label":"On time","tone":"success"},{"id":"routeCard","component":"Card","variant":"tonal","child":"routeGroup"},{"id":"routeGroup","component":"Column","children":["route","airline","date"]},{"id":"route","component":"Text","text":{"path":"/route"},"variant":"h2"},{"id":"airline","component":"Text","text":{"path":"/airline"},"tone":"muted"},{"id":"date","component":"Text","text":{"path":"/date"},"variant":"label"},{"id":"stats","component":"Row","justify":"spaceBetween","children":["gate","seat","duration"]},{"id":"gate","component":"Metric","value":{"path":"/gate"},"label":"Boarding"},{"id":"seat","component":"Metric","value":{"path":"/seat"},"label":"Seat"},{"id":"duration","component":"Metric","value":{"path":"/duration"},"label":"Duration"},{"id":"divider","component":"Divider"},{"id":"checkinLabel","component":"Text","text":"Open boarding pass"},{"id":"checkin","component":"Button","child":"checkinLabel","action":{"name":"open_boarding_pass","context":{"flight":"6E681"}}}]}}"""
    ),
    A2UIExample(
        "Product analytics",
        "Metrics, progress bars and status indicators",
        """{"version":"v0.9","createSurface":{"surfaceId":"analytics","catalogId":"basic","sendDataModel":false}}
{"version":"v0.9","updateDataModel":{"surfaceId":"analytics","value":{"title":"Weekly product pulse","subtitle":"14–20 July","users":"12.8K","sessions":"31.4K","conversion":"4.8%","retention":"72%","goal":"Quarterly activation goal","release":"Android renderer v0.2"}}}
{"version":"v0.9","updateComponents":{"surfaceId":"analytics","components":[{"id":"root","component":"Column","spacing":16,"children":["header","metrics","goalCard","releaseCard","refresh"]},{"id":"header","component":"Row","justify":"spaceBetween","children":["headerText","live"]},{"id":"headerText","component":"Column","children":["title","subtitle"]},{"id":"title","component":"Text","text":{"path":"/title"},"variant":"h2"},{"id":"subtitle","component":"Text","text":{"path":"/subtitle"},"tone":"muted"},{"id":"live","component":"Chip","label":"Live","tone":"success"},{"id":"metrics","component":"Row","justify":"spaceBetween","children":["users","sessions","conversion"]},{"id":"users","component":"Metric","value":{"path":"/users"},"label":"Users"},{"id":"sessions","component":"Metric","value":{"path":"/sessions"},"label":"Sessions"},{"id":"conversion","component":"Metric","value":{"path":"/conversion"},"label":"Conversion"},{"id":"goalCard","component":"Card","variant":"outlined","child":"goalGroup"},{"id":"goalGroup","component":"Column","children":["goal","retention"]},{"id":"goal","component":"Text","text":{"path":"/goal"},"variant":"label"},{"id":"retention","component":"ProgressBar","label":{"path":"/retention"},"value":0.72},{"id":"releaseCard","component":"Card","variant":"tonal","child":"releaseGroup"},{"id":"releaseGroup","component":"Row","justify":"spaceBetween","children":["release","ready"]},{"id":"release","component":"Text","text":{"path":"/release"},"variant":"h3"},{"id":"ready","component":"Chip","label":"Ready","tone":"success"},{"id":"refreshLabel","component":"Text","text":"Refresh metrics"},{"id":"refresh","component":"Button","variant":"secondary","child":"refreshLabel","action":{"name":"refresh_metrics"}}]}}"""
    ),
    A2UIExample(
        "Shopping checkout",
        "Product image, order summary, delivery and payment",
        """{"version":"v0.9","createSurface":{"surfaceId":"checkout","catalogId":"basic","sendDataModel":true}}
{"version":"v0.9","updateDataModel":{"surfaceId":"checkout","value":{"title":"Review your order","product":"Noise-cancelling headphones","variant":"Midnight black · 1 item","price":"₹7,999","delivery":"Delivery by Friday","total":"₹8,148"}}}
{"version":"v0.9","updateComponents":{"surfaceId":"checkout","components":[{"id":"root","component":"Column","spacing":14,"children":["title","productCard","deliveryCard","gift","address","summaryCard","pay"]},{"id":"title","component":"Text","text":{"path":"/title"},"variant":"h2"},{"id":"productCard","component":"Card","variant":"outlined","child":"productGroup"},{"id":"productGroup","component":"Column","children":["productImage","product","variant","price"]},{"id":"productImage","component":"Image","url":"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200","alt":"Headphones"},{"id":"product","component":"Text","text":{"path":"/product"},"variant":"h3"},{"id":"variant","component":"Text","text":{"path":"/variant"},"tone":"muted"},{"id":"price","component":"Text","text":{"path":"/price"},"variant":"h3","tone":"secondary"},{"id":"deliveryCard","component":"Card","variant":"tonal","child":"delivery"},{"id":"delivery","component":"Text","text":{"path":"/delivery"},"variant":"label"},{"id":"gift","component":"CheckBox","label":"This is a gift","value":false},{"id":"address","component":"TextField","label":"Delivery instructions","value":"Leave with security","variant":"longText"},{"id":"summaryCard","component":"Card","child":"summary"},{"id":"summary","component":"Row","justify":"spaceBetween","children":["totalLabel","total"]},{"id":"totalLabel","component":"Text","text":"Total","variant":"h3"},{"id":"total","component":"Text","text":{"path":"/total"},"variant":"h3","tone":"accent"},{"id":"payLabel","component":"Text","text":"Pay securely"},{"id":"pay","component":"Button","child":"payLabel","action":{"name":"complete_checkout","context":{"cartId":"cart-1024"}}}]}}"""
    ),
    A2UIExample(
        "Concert ticket",
        "Poster-style event ticket with venue and entry action",
        """{"version":"v0.9","createSurface":{"surfaceId":"ticket","catalogId":"basic","sendDataModel":false}}
{"version":"v0.9","updateDataModel":{"surfaceId":"ticket","value":{"event":"Monsoon Sessions","artist":"The Midnight Raag Collective","date":"Saturday · 8:00 PM","venue":"Phoenix Arena, Pune","zone":"Gold Zone","entry":"Entry B","ticket":"MRS-2048"}}}
{"version":"v0.9","updateComponents":{"surfaceId":"ticket","components":[{"id":"root","component":"Column","spacing":14,"children":["poster","sold","event","artist","divider","details","ticketCard","open"]},{"id":"poster","component":"Image","url":"https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200","alt":"Concert crowd"},{"id":"sold","component":"Chip","label":"Almost sold out","tone":"warning"},{"id":"event","component":"Text","text":{"path":"/event"},"variant":"h2"},{"id":"artist","component":"Text","text":{"path":"/artist"},"tone":"muted"},{"id":"divider","component":"Divider"},{"id":"details","component":"Column","children":["date","venue"]},{"id":"date","component":"Text","text":{"path":"/date"},"variant":"label"},{"id":"venue","component":"Text","text":{"path":"/venue"}},{"id":"ticketCard","component":"Card","variant":"tonal","child":"ticketGroup"},{"id":"ticketGroup","component":"Row","justify":"spaceBetween","children":["zone","entry","ticket"]},{"id":"zone","component":"Metric","value":{"path":"/zone"},"label":"Access"},{"id":"entry","component":"Metric","value":{"path":"/entry"},"label":"Gate"},{"id":"ticket","component":"Metric","value":{"path":"/ticket"},"label":"Ticket"},{"id":"openLabel","component":"Text","text":"Show ticket"},{"id":"open","component":"Button","child":"openLabel","action":{"name":"show_event_ticket"}}]}}"""
    ),
    A2UIExample(
        "Wellness dashboard",
        "Daily health summary with goals and controls",
        """{"version":"v0.9","createSurface":{"surfaceId":"wellness","catalogId":"basic","sendDataModel":true}}
{"version":"v0.9","updateDataModel":{"surfaceId":"wellness","value":{"title":"Good afternoon, Chinmay","subtitle":"You are building a consistent week","steps":"7,842","sleep":"7h 18m","water":"1.8 L","activity":"Daily activity","sleepGoal":"Sleep target","note":"How are you feeling today?"}}}
{"version":"v0.9","updateComponents":{"surfaceId":"wellness","components":[{"id":"root","component":"Column","spacing":16,"children":["title","subtitle","metrics","activityCard","sleepCard","mood","note","save"]},{"id":"title","component":"Text","text":{"path":"/title"},"variant":"h2"},{"id":"subtitle","component":"Text","text":{"path":"/subtitle"},"tone":"muted"},{"id":"metrics","component":"Row","justify":"spaceBetween","children":["steps","sleep","water"]},{"id":"steps","component":"Metric","value":{"path":"/steps"},"label":"Steps"},{"id":"sleep","component":"Metric","value":{"path":"/sleep"},"label":"Sleep"},{"id":"water","component":"Metric","value":{"path":"/water"},"label":"Water"},{"id":"activityCard","component":"Card","variant":"outlined","child":"activity"},{"id":"activity","component":"ProgressBar","label":{"path":"/activity"},"value":0.78},{"id":"sleepCard","component":"Card","variant":"tonal","child":"sleepProgress"},{"id":"sleepProgress","component":"ProgressBar","label":{"path":"/sleepGoal"},"value":0.91},{"id":"mood","component":"Slider","label":"Energy level","min":1,"max":10,"value":7},{"id":"note","component":"TextField","label":{"path":"/note"},"value":"Focused and calm","variant":"longText"},{"id":"saveLabel","component":"Text","text":"Save daily check-in"},{"id":"save","component":"Button","variant":"secondary","child":"saveLabel","action":{"name":"save_wellness_checkin"}}]}}"""
    ),
    A2UIExample(
        "Editorial story",
        "Magazine-style content card with image and reading action",
        """{"version":"v0.9","createSurface":{"surfaceId":"story","catalogId":"basic","sendDataModel":false}}
{"version":"v0.9","updateDataModel":{"surfaceId":"story","value":{"category":"TECHNOLOGY","title":"Why native generative interfaces are becoming practical","summary":"A2UI separates intent, state and rendering so the same agent response can become a native experience on every platform.","author":"By A2UI Studio","reading":"6 min read"}}}
{"version":"v0.9","updateComponents":{"surfaceId":"story","components":[{"id":"root","component":"Column","spacing":14,"children":["cover","meta","title","summary","authorCard","actions"]},{"id":"cover","component":"Image","url":"https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200","alt":"Circuit board"},{"id":"meta","component":"Row","justify":"spaceBetween","children":["category","reading"]},{"id":"category","component":"Chip","label":{"path":"/category"}},{"id":"reading","component":"Text","text":{"path":"/reading"},"tone":"muted"},{"id":"title","component":"Text","text":{"path":"/title"},"variant":"h2"},{"id":"summary","component":"Text","text":{"path":"/summary"}},{"id":"authorCard","component":"Card","variant":"outlined","child":"author"},{"id":"author","component":"Text","text":{"path":"/author"},"variant":"label"},{"id":"actions","component":"Row","justify":"spaceBetween","children":["save","read"]},{"id":"saveLabel","component":"Text","text":"Save"},{"id":"save","component":"Button","variant":"outlined","child":"saveLabel","action":{"name":"save_story"}},{"id":"readLabel","component":"Text","text":"Read article"},{"id":"read","component":"Button","child":"readLabel","action":{"name":"open_story"}}]}}"""
    ),
    A2UIExample(
        "Account onboarding",
        "A focused setup flow with progress and preferences",
        """{"version":"v0.9","createSurface":{"surfaceId":"onboarding","catalogId":"basic","sendDataModel":true}}
{"version":"v0.9","updateDataModel":{"surfaceId":"onboarding","value":{"step":"STEP 2 OF 3","title":"Make the app yours","subtitle":"A few preferences help us tailor the experience.","name":"Chinmay","role":"AI and Android developer"}}}
{"version":"v0.9","updateComponents":{"surfaceId":"onboarding","components":[{"id":"root","component":"Column","spacing":14,"children":["step","progress","title","subtitle","name","role","updates","analytics","actions"]},{"id":"step","component":"Chip","label":{"path":"/step"}},{"id":"progress","component":"ProgressBar","label":"Profile setup","value":0.66},{"id":"title","component":"Text","text":{"path":"/title"},"variant":"h2"},{"id":"subtitle","component":"Text","text":{"path":"/subtitle"},"tone":"muted"},{"id":"name","component":"TextField","label":"Display name","value":{"path":"/name"}},{"id":"role","component":"TextField","label":"What do you do?","value":{"path":"/role"}},{"id":"updates","component":"CheckBox","label":"Send product updates","value":true},{"id":"analytics","component":"CheckBox","label":"Share anonymous usage analytics","value":false},{"id":"actions","component":"Row","justify":"spaceBetween","children":["back","continue"]},{"id":"backLabel","component":"Text","text":"Back"},{"id":"back","component":"Button","variant":"borderless","child":"backLabel","action":{"name":"previous_step"}},{"id":"continueLabel","component":"Text","text":"Continue"},{"id":"continue","component":"Button","child":"continueLabel","action":{"name":"complete_preferences"}}]}}"""
    )
)
